// You are given two strings s and t.
// String t is generated by random shuffling string s and then add one more letter at a random position.

// Return the letter that was added to t.

// Example 1:

// Input: s = "abcd", t = "abcde"
// Output: "e"
// Explanation: 'e' is the letter that was added.
// Example 2:

// Input: s = "", t = "y"
// Output: "y"

// Constraints:

// 0 <= s.length <= 1000
// t.length == s.length + 1
// s and t consist of lowercase English letters.

// IP: 2 strings, t = s + 1,
// OP: string, the char added to t
// C: only lowercase, 0 <= s.length <= 1000
// loop thro t
// IF the letter does NOT exist in s
// return that letter
var _findTheDifference = function(s, t) {
    if (t.length === 2) {
        if (s[0] === t[0]) {
            return t[1];
        } else {
            return t[0];
        }
    }

    for (let i = 0; i < t.length; i++) {
        let inS = s.includes(t[i]);
        if (!inS) {
            return t[i];
        }
    }
    return "did not find."
};


var findTheDifference = function(s, t) {
    // if (t.length === 2) {
    //     if (s[0] === t[0]) {
    //         return t[1];
    //     } else {
    //         return t[0];
    //     }
    // }
    let newS = s.slice();
    let newT = t.slice();
    while (newS.length >= 0) {
        if (newS.length === 0) {
            return newT;
        }
        if (newT.includes(newS[0])) {
            const newTIndex = newT.indexOf(newS[0]);
            newS = newS.slice(1, newS.length);
            newT = newT.slice(0, newTIndex) + newT.slice(newTIndex + 1, newT.length);
        }
    }

};

console.log(findTheDifference("abcd", "abcde")) // e
console.log(findTheDifference("abcd", "abecd")) // e
console.log(findTheDifference("ab", "aba")) // a
// PASSED ALL LEETCODES tests
